"use client";
import { useMemo,useState } from "react";
import { Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import styles from "./MetaAds.module.css";
import { Campanha,Dashboard,Insight,METRICAS,n,objetivo } from "./metaTypes";
type Props={dashboard:Dashboard;money:Intl.NumberFormat;inteiro:Intl.NumberFormat;formatar:(v:number,t:string)=>string};
const soma=(lista:Campanha[],campo:keyof Insight)=>lista.reduce((t,c)=>t+n(c[campo]),0);
export default function MetaCampaignReport({dashboard,money,inteiro,formatar}:Props){
 const[busca,setBusca]=useState(""),[status,setStatus]=useState("todos"),[obj,setObj]=useState("todos"),[campanha,setCampanha]=useState("todas"),[metrica,setMetrica]=useState("gasto");
 const objetivos=useMemo(()=>Array.from(new Set(dashboard.campanhas.map(c=>c.objetivo).filter(Boolean) as string[])),[dashboard.campanhas]);
 const lista=useMemo(()=>dashboard.campanhas.filter(c=>(campanha==="todas"||c.id===campanha)&&(status==="todos"||String(c.status).toUpperCase()===status)&&(obj==="todos"||c.objetivo===obj)&&(!busca||c.nome.toLowerCase().includes(busca.toLowerCase()))),[dashboard.campanhas,campanha,status,obj,busca]);
 const r={gasto:soma(lista,"gasto"),leads:soma(lista,"leads"),formularios:soma(lista,"formularios"),conversas:soma(lista,"conversas"),compras:soma(lista,"compras"),receita:soma(lista,"receita"),cliques:soma(lista,"cliques"),impressoes:soma(lista,"impressoes")};
 const d={cpl:r.leads?r.gasto/r.leads:0,custoConversa:r.conversas?r.gasto/r.conversas:0,cpa:r.compras?r.gasto/r.compras:0,cpc:r.cliques?r.gasto/r.cliques:0,ctr:r.impressoes?r.cliques/r.impressoes*100:0,roas:r.gasto?r.receita/r.gasto:0};
 const met=METRICAS.find(m=>m.key===metrica)||METRICAS[0];
 const grafico=[...lista].sort((a,b)=>n(b[metrica as keyof Campanha])-n(a[metrica as keyof Campanha])).slice(0,12).map(c=>({...c,nomeCurto:c.nome.length>24?c.nome.slice(0,24)+"…":c.nome}));
 const exportar=()=>{const cab=["Campanha","Status","Objetivo","Investimento","Leads","Formulários","Conversas","Compras","Receita","CPL","Custo por conversa","CPA","CPC","CTR","CPM","Frequência","ROAS","Alcance","Impressões","Cliques"];const rows=lista.map(c=>[c.nome,c.status,objetivo(c.objetivo),c.gasto,c.leads,c.formularios,c.conversas,c.compras,c.receita,c.cpl,c.custoConversa,c.custoCompra,c.cpc,c.ctr,c.cpm,c.frequencia,c.roas,c.alcance,c.impressoes,c.cliques]);const csv="\uFEFF"+[cab,...rows].map(row=>row.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="central-ads-campanhas.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className={styles.campaignPage}>
  <section className={styles.campaignIntro}><div><span className={styles.eyebrow}>RELATÓRIO OPERACIONAL</span><h2>Campanhas</h2><p>Custos e resultados atualizados diretamente da conta de anúncios.</p></div><button className={styles.exportButton} onClick={exportar}>↓ Exportar relatório CSV</button></section>
  <section className={styles.filterBar}><label>Buscar<input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Nome da campanha"/></label><label>Campanha<select value={campanha} onChange={e=>setCampanha(e.target.value)}><option value="todas">Todas as campanhas</option>{dashboard.campanhas.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todos</option><option value="ACTIVE">Ativas</option><option value="PAUSED">Pausadas</option><option value="WITH_ISSUES">Com problema</option></select></label><label>Objetivo<select value={obj} onChange={e=>setObj(e.target.value)}><option value="todos">Todos</option>{objetivos.map(o=><option key={o} value={o}>{objetivo(o)}</option>)}</select></label></section>
  <section className={styles.campaignKpis}><Mini label="Investimento" value={money.format(r.gasto)}/><Mini label="Leads" value={inteiro.format(r.leads)}/><Mini label="Conversas" value={inteiro.format(r.conversas)}/><Mini label="CPL" value={money.format(d.cpl)}/><Mini label="Custo/conversa" value={money.format(d.custoConversa)}/><Mini label="CPA" value={money.format(d.cpa)}/><Mini label="CPC" value={money.format(d.cpc)}/><Mini label="CTR" value={d.ctr.toLocaleString("pt-BR",{maximumFractionDigits:2})+"%"}/><Mini label="ROAS" value={d.roas.toLocaleString("pt-BR",{maximumFractionDigits:2})+"x"}/><Mini label="Receita atribuída" value={money.format(r.receita)}/></section>
  <section className={styles.reportCard}><div className={styles.graphToolbar}><div><h3>Comparar campanhas</h3><p>O gráfico muda conforme o indicador selecionado.</p></div><select value={metrica} onChange={e=>setMetrica(e.target.value)}>{METRICAS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></div><ResponsiveContainer width="100%" height={330}><BarChart data={grafico} layout="vertical" margin={{left:12,right:30}}><CartesianGrid strokeDasharray="3 3" stroke="#e8edf5" horizontal={false}/><XAxis type="number" fontSize={10}/><YAxis type="category" dataKey="nomeCurto" width={165} fontSize={9}/><Tooltip formatter={v=>formatar(n(v),met.tipo)} labelFormatter={(_,payload)=>payload?.[0]?.payload?.nome||""}/><Bar dataKey={metrica} name={met.label} fill="#2563eb" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></section>
  <section className={styles.campaignTableCard}><div className={styles.tableTitle}><div><h3>Visão geral detalhada</h3><p>{lista.length} campanha(s) no filtro atual · role para ver todas as métricas</p></div></div><div className={styles.campaignTableWrap}><table className={styles.campaignTable}><thead><tr><th>Campanha</th><th>Status</th><th>Objetivo</th><th>Investimento</th><th>Leads</th><th>Formulários</th><th>Conversas</th><th>Compras</th><th>Receita</th><th>CPL</th><th>Custo/conversa</th><th>CPA</th><th>CPC</th><th>CTR</th><th>CPM</th><th>Frequência</th><th>ROAS</th><th>Alcance</th><th>Impressões</th><th>Cliques</th></tr></thead><tbody>{lista.map(c=><tr key={c.id}><td><b title={c.nome}>{c.nome}</b><small>ID {c.id}</small></td><td><Status value={c.status}/></td><td>{objetivo(c.objetivo)}</td><td>{money.format(c.gasto)}</td><td>{inteiro.format(c.leads)}</td><td>{inteiro.format(c.formularios)}</td><td>{inteiro.format(c.conversas)}</td><td>{inteiro.format(c.compras)}</td><td>{money.format(c.receita)}</td><td>{money.format(c.cpl)}</td><td>{money.format(c.custoConversa)}</td><td>{money.format(c.custoCompra)}</td><td>{money.format(c.cpc)}</td><td>{c.ctr.toLocaleString("pt-BR",{maximumFractionDigits:2})}%</td><td>{money.format(c.cpm)}</td><td>{c.frequencia.toLocaleString("pt-BR",{maximumFractionDigits:2})}</td><td>{c.roas.toLocaleString("pt-BR",{maximumFractionDigits:2})}x</td><td>{inteiro.format(c.alcance)}</td><td>{inteiro.format(c.impressoes)}</td><td>{inteiro.format(c.cliques)}</td></tr>)}</tbody></table></div></section>
 </div>;
}
function Mini({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function Status({value}:{value:string}){const s=String(value||"").toUpperCase(),ativo=s==="ACTIVE",problema=["WITH_ISSUES","ERROR","DISAPPROVED"].includes(s);return <span className={ativo?styles.campaignActive:problema?styles.campaignProblem:styles.campaignPaused}>{ativo?"Ativa":problema?"Com problema":"Pausada"}</span>}
