"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import styles from "./MetaAds.module.css";
import { Campanha, CORES, Dashboard, Insight, InstagramDashboard, METRICAS, n, Preferencias, Serie } from "./metaTypes";

type Props={dashboard:Dashboard;resumo:Insight;preferencias:Preferencias;money:Intl.NumberFormat;inteiro:Intl.NumberFormat;formatar:(v:number,t:string)=>string;mensal:Serie[];propostas:{atual:number;anterior:number;vendas:number;receita:number;variacao:number|null};instagram:InstagramDashboard|null};
const GRAFAVEIS=METRICAS.filter(m=>!["formularios","video100","thruplays"].includes(m.key));

export default function MetaExecutiveDashboard({dashboard,resumo,preferencias,money,inteiro,formatar,mensal,propostas,instagram}:Props){
 const[m1,setM1]=useState("gasto"),[m2,setM2]=useState("leads"),[rankKey,setRankKey]=useState("gasto");
 const meta1=METRICAS.find(m=>m.key===m1)||METRICAS[0],meta2=METRICAS.find(m=>m.key===m2)||METRICAS[1],rankMeta=METRICAS.find(m=>m.key===rankKey)||METRICAS[0];
 const metricas=METRICAS.filter(m=>preferencias.metricasVisiveis.includes(m.key)).slice(0,10),ativas=dashboard.campanhas.filter(c=>String(c.status).toUpperCase()==="ACTIVE").length,comGasto=dashboard.campanhas.filter(c=>c.gasto>0);
 const ranking=useMemo(()=>[...comGasto].sort((a,b)=>n(b[rankKey as keyof Campanha])-n(a[rankKey as keyof Campanha])).slice(0,7),[comGasto,rankKey]);
 const pizza=comGasto.slice(0,6).map(c=>({name:c.nome,value:c.gasto})),totalRank=Math.max(...ranking.map(c=>n(c[rankKey as keyof Campanha])),1);
 const score=Math.max(0,Math.min(100,Math.round((resumo.ctr>=1?25:12)+(resumo.cpc>0&&resumo.cpc<=5?25:12)+(resumo.leads>0?25:8)+(resumo.roas>=1?25:resumo.roas>0?12:5))));
 return <div className={styles.dashboardStack}>
  <section className={styles.executiveHero}><div><span className={styles.eyebrow}>RESUMO EXECUTIVO</span><h2>O que está acontecendo com seus anúncios</h2><p>{ativas} campanha(s) ativa(s), {inteiro.format(resumo.leads)} lead(s) e {money.format(resumo.gasto)} investidos no período.</p><div className={styles.heroPills}><span>Alcance {inteiro.format(resumo.alcance)}</span><span>{inteiro.format(resumo.conversas)} conversas</span><span>{resumo.roas.toLocaleString("pt-BR",{maximumFractionDigits:2})}x de ROAS</span></div></div><div className={styles.healthScore}><div style={{"--score":`${score*3.6}deg`} as React.CSSProperties}><strong>{score}</strong><span>/100</span></div><p>Saúde da mídia</p><small>Eficiência, volume e retorno.</small></div></section>
  <section className={styles.executiveKpis}>{metricas.map(m=><MetricCard key={m.key} label={m.label} value={formatar(n(resumo[m.key as keyof Insight]),m.tipo)} note={m.note} variacao={dashboard.comparacao.variacoes[m.key]} inverso={"inverso" in m&&Boolean(m.inverso)}/>)}<MetricCard label="Propostas no CRM" value={inteiro.format(propostas.atual)} note="Entradas comerciais do período" variacao={propostas.variacao}/><MetricCard label="Vendas no CRM" value={inteiro.format(propostas.vendas)} note={money.format(propostas.receita)+" em planos"}/></section>
  <section className={styles.insightGrid}>
   <article className={[styles.reportCard,styles.reportWide].join(" ")}><CardHead title="Evolução do desempenho" subtitle="Escolha exatamente quais indicadores deseja comparar."/><div className={styles.metricChooser}><label>Indicador principal<select value={m1} onChange={e=>setM1(e.target.value)}>{GRAFAVEIS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label><label>Comparar com<select value={m2} onChange={e=>setM2(e.target.value)}>{GRAFAVEIS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select></label></div><ResponsiveContainer width="100%" height={330}><AreaChart data={dashboard.serieDiaria}><defs><linearGradient id="wolfMetaArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.32}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#e8edf5" vertical={false}/><XAxis dataKey="data" tickFormatter={v=>String(v).slice(5)} fontSize={10}/><YAxis yAxisId="a" fontSize={10}/><YAxis yAxisId="b" orientation="right" fontSize={10}/><Tooltip formatter={(v,name)=>[formatar(n(v),name===meta1.label?meta1.tipo:meta2.tipo),name]}/><Legend/><Area yAxisId="a" type="monotone" dataKey={m1} name={meta1.label} stroke="#2563eb" strokeWidth={3} fill="url(#wolfMetaArea)"/><Line yAxisId="b" type="monotone" dataKey={m2} name={meta2.label} stroke="#7c3aed" strokeWidth={3} dot={false}/></AreaChart></ResponsiveContainer></article>
   <article className={styles.reportCard}><CardHead title="Distribuição do investimento" subtitle="Onde cada real foi aplicado."/><ResponsiveContainer width="100%" height={270}><PieChart><Pie data={pizza} dataKey="value" nameKey="name" innerRadius={64} outerRadius={96} paddingAngle={3}>{pizza.map((_,i)=><Cell key={i} fill={CORES[i%CORES.length]}/>)}</Pie><Tooltip formatter={v=>money.format(n(v))}/><Legend iconType="circle" wrapperStyle={{fontSize:10}}/></PieChart></ResponsiveContainer></article>
   <article className={styles.reportCard}><CardHead title="Funil de aquisição" subtitle="Do anúncio ao resultado comercial."/><ResponsiveContainer width="100%" height={270}><BarChart layout="vertical" data={[{nome:"Impressões",valor:resumo.impressoes},{nome:"Cliques",valor:resumo.cliques},{nome:"Leads",valor:resumo.leads},{nome:"Propostas",valor:propostas.atual},{nome:"Vendas",valor:propostas.vendas}]}><CartesianGrid strokeDasharray="3 3" stroke="#e8edf5" horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="nome" width={72} fontSize={10}/><Tooltip formatter={v=>inteiro.format(n(v))}/><Bar dataKey="valor" fill="#16a34a" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer></article>
   <article className={[styles.reportCard,styles.reportWide].join(" ")}><CardHead title="Comparativo mês a mês" subtitle="O histórico acompanha os indicadores escolhidos no gráfico acima."/><ResponsiveContainer width="100%" height={330}><BarChart data={mensal}><CartesianGrid strokeDasharray="3 3" stroke="#e8edf5" vertical={false}/><XAxis dataKey="mes" fontSize={10}/><YAxis yAxisId="a" fontSize={10}/><YAxis yAxisId="b" orientation="right" fontSize={10}/><Tooltip formatter={(v,name)=>[formatar(n(v),name===meta1.label?meta1.tipo:meta2.tipo),name]}/><Legend/><Bar yAxisId="a" dataKey={m1} name={meta1.label} fill="#2563eb" radius={[6,6,0,0]}/><Bar yAxisId="b" dataKey={m2} name={meta2.label} fill="#7c3aed" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article>
   <article className={styles.reportCard}><CardHead title="Ranking de campanhas" subtitle="Troque o critério e descubra as melhores."/><select className={styles.inlineSelect} value={rankKey} onChange={e=>setRankKey(e.target.value)}>{GRAFAVEIS.map(m=><option key={m.key} value={m.key}>{m.label}</option>)}</select><div className={styles.rankingList}>{ranking.map((c,i)=>{const value=n(c[rankKey as keyof Campanha]);return <div key={c.id}><div><span>{i+1}</span><b title={c.nome}>{c.nome}</b><strong>{formatar(value,rankMeta.tipo)}</strong></div><i><em style={{width:`${Math.max(4,value/totalRank*100)}%`}}/></i></div>})}</div></article>
   <article className={styles.reportCard}><CardHead title="Instagram conectado" subtitle="Visão orgânica opcional dentro da Central."/>{instagram?<div className={styles.instagramSummary}><strong>@{instagram.perfil.username}</strong><div><span><b>{inteiro.format(n(instagram.perfil.seguidores))}</b> seguidores</span><span><b>{inteiro.format(n(instagram.resumo.reach))}</b> alcançados</span><span><b>{inteiro.format(n(instagram.resumo.total_interactions))}</b> interações</span><span><b>{inteiro.format(n(instagram.resumo.profile_views))}</b> visitas</span></div></div>:<div className={styles.softEmpty}>Conecte um Instagram profissional em Configurações para incluir crescimento e conteúdo neste painel.</div>}</article>
  </section>
 </div>;
}
function MetricCard({label,value,note,variacao,inverso=false}:{label:string;value:string;note:string;variacao?:number|null;inverso?:boolean}){const bom=variacao!=null&&(inverso?variacao<=0:variacao>=0);return <article className={styles.metricCard}><span>{label}</span><strong>{value}</strong><small>{note}</small>{variacao!==undefined&&<em className={variacao===null?styles.neutral:bom?styles.up:styles.down}>{variacao===null?"Novo":`${variacao>=0?"↑":"↓"} ${Math.abs(variacao).toLocaleString("pt-BR",{maximumFractionDigits:1})}%`}</em>}</article>}
function CardHead({title,subtitle}:{title:string;subtitle:string}){return <header className={styles.cardHead}><div><h3>{title}</h3><p>{subtitle}</p></div></header>}
