-- Motor genérico de automações do CRM para os fluxos Wolf.
-- Execute uma única vez no SQL Editor do Supabase.

alter table public.proposta
  add column if not exists canal_id bigint,
  add column if not exists fluxo_id bigint,
  add column if not exists updated_at timestamptz not null default now();

create or replace function public.wolf_proposta_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists wolf_proposta_updated_at on public.proposta;
create trigger wolf_proposta_updated_at
before update on public.proposta
for each row execute function public.wolf_proposta_updated_at();

create table if not exists public.crm_automacao_estado (
  proposta_id bigint primary key references public.proposta(id) on delete cascade,
  workspace_id text not null,
  snapshot jsonb not null default '{}'::jsonb,
  proposta_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists crm_automacao_estado_workspace_idx
  on public.crm_automacao_estado(workspace_id);

create table if not exists public.crm_automacao_eventos (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  proposta_id bigint not null references public.proposta(id) on delete cascade,
  fluxo_id bigint not null,
  no_id text not null,
  campo text not null,
  valor_anterior text,
  valor_novo text,
  proposta_updated_at timestamptz not null,
  canal_id bigint,
  numero text,
  status text not null default 'processando',
  erro text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (proposta_id, no_id, proposta_updated_at)
);

create index if not exists crm_automacao_eventos_workspace_idx
  on public.crm_automacao_eventos(workspace_id, created_at desc);

alter table public.crm_automacao_estado enable row level security;
alter table public.crm_automacao_eventos enable row level security;

-- O backend usa a service role. Usuários autenticados podem consultar somente
-- registros do workspace conforme as políticas globais do projeto.
grant all on public.crm_automacao_estado to service_role;
grant all on public.crm_automacao_eventos to service_role;
grant usage, select on all sequences in schema public to service_role;
