-- Dashboard avançado da Central Meta ADS.
-- Preferências, alertas e Instagram ficam isolados por workspace.

create table if not exists public.meta_ads_preferencias (
  workspace_id text primary key,
  metricas_visiveis jsonb not null default
    '["gasto","leads","formularios","conversas","compras","receita","cpl","custoConversa","custoCompra","roas","alcance","cliques"]'::jsonb,
  graficos_visiveis jsonb not null default
    '["evolucao","comparativoMensal","distribuicao","funil"]'::jsonb,
  regras_alerta jsonb not null default '[]'::jsonb,
  popup_ativo boolean not null default true,
  som_ativo boolean not null default false,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.meta_ads_preferencias enable row level security;
revoke all on table public.meta_ads_preferencias from anon, authenticated;

comment on table public.meta_ads_preferencias is
  'Preferências visuais e regras de alerta da Central Meta ADS, separadas por workspace.';

alter table public.meta_ads_conexoes
  add column if not exists instagram_user_id text,
  add column if not exists instagram_username text,
  add column if not exists instagram_name text,
  add column if not exists instagram_profile_picture_url text,
  add column if not exists instagram_accounts_snapshot jsonb not null default '[]'::jsonb,
  add column if not exists instagram_status text;

create table if not exists public.meta_instagram_snapshots (
  id bigint generated by default as identity primary key,
  workspace_id text not null,
  instagram_user_id text not null,
  snapshot_date date not null default current_date,
  followers_count bigint not null default 0,
  media_count bigint not null default 0,
  views bigint not null default 0,
  reach bigint not null default 0,
  accounts_engaged bigint not null default 0,
  total_interactions bigint not null default 0,
  profile_views bigint not null default 0,
  created_at timestamptz not null default now(),
  unique (workspace_id, instagram_user_id, snapshot_date)
);

create index if not exists meta_instagram_snapshots_workspace_idx
  on public.meta_instagram_snapshots (workspace_id, snapshot_date desc);

alter table public.meta_instagram_snapshots enable row level security;
revoke all on table public.meta_instagram_snapshots from anon, authenticated;

comment on table public.meta_instagram_snapshots is
  'Histórico diário de insights do Instagram para calcular crescimento por workspace.';

create or replace function public.meta_ads_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists meta_ads_preferencias_touch on public.meta_ads_preferencias;
create trigger meta_ads_preferencias_touch
before update on public.meta_ads_preferencias
for each row execute function public.meta_ads_touch_updated_at();
